name: YAML Linting
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - "**/*.yml"
      - ".yamllint"
jobs:
  yamllint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          format: github
        env:
          LANG: C.UTF-8
